service: ubd-serverless
frameworkVersion: '3'
useDotenv: true
custom:
  wsgi:
    app: app.app
  pythonRequirements:
    fileName: requirements-prod.txt
plugins:
  - serverless-wsgi
  - serverless-python-requirements
provider:
  name: aws
  runtime: python3.8
  environment:
    STRIP_STAGE_PATH: yes
    S3_BUCKET: ${env:S3_BUCKET}
    NEPTUNEDBRO: ${env:NEPTUNEDBRO}
    CLIENT_SECRET: ${env:CLIENT_SECRET}
    CLIENT_ID: ${env:CLIENT_ID}
    APP_SECRET_ARN: ${env:APP_SECRET_ARN}
  vpc:
    securityGroupIds:
      - ${env:UBD_DEFAULT_SG}
      - ${env:UBD_NEPTUNE_SG}
    subnetIds:
      - ${env:UBD_PRIVATE_SUBNET_ID}
  deploymentBucket:
    name: ubd-deployments
    maxPreviousDeploymentArtifacts: 10
    blockPublicAccess: true
    skipPolicySetup: true
    versioning: true
    serverSideEncryption: aws:kms
    sseKMSKeyId: ${env:KMS_ARN}
    tags:
      ProjectName: ubd
      IAMUsername: vinverso
  stage: production
  region: us-west-1
  profile: ubd
  stackName: ubd-stack
  tags:
    ProjectName: ubd
    IAMUsername: vinverso
  stackTags:
    ProjectName: ubd
    IAMUsername: vinverso
  deploymentMethod: direct
  disableRollback: true
  tracing:
    apiGateway: true
    lambda: true
functions:
  api:
    handler: wsgi_handler.handler
    events:
      - httpApi: '*'
    layers:
      - arn:aws:lambda:us-west-1:770693421928:layer:Klayers-p38-Pillow:2
package:
  patterns:
    - '!venv/**'
    - '!tests/**'
    - '!.env.production'