values = ["Precipitation",
"Surface Pressure",
"Surface Radiation Budget",
"Surface Winds",
"Surface Air Temperature",
"Water Vapour (surface)",
"Earth Radiation Budget",
"Lightning",
"Air Temperature Profile",
"Cloud Properties",
"Wind Speed and Direction (upper-air)",
"Aerosol Properties",
"Carbon Dioxide",
"Methane",
"Greenhouse Gases",
"Ozone",
"Nitrogen Dioxide",
"Sulfur Dioxide",
"HCHO",
"Carbon Monoxide",
"River Discharge",
"Groundwater",
"Lakes",
"Soil Moisture",
"Snow",
"Glaciers",
"Ice Sheets and Shelves",
"Permafrost",
"Albedo",
"Land Cover",
"Photosynthetically Active Radiation",
"Leaf Area Index (LAI)",
"Above-ground Biomass",
"Soil Carbon",
"Land Surface Temperature",
"Fire",
"Heat Flux",
"Anthropogenic Greenhouse Gas Fluxes",
"Anthropogenic Water Use",
"Ocean Surface Heat Flux",
"Sea Ice",
"Sea Level",
"Sea State",
"Sea Surface Salinity",
"Subsurface Currents",
"Subsurface Salinity",
"Subsurface Temperature",
"Surface Currents",
"Surface Stress",
"Inorganic Carbon",
"Nitrous Oxide",
"Nutrients",
"Ocean Colour",
"Oxygen",
"Transient Tracers",
"Marine Habitat Properties",
"Plankton"]