name: Unit Testing

on:
#   push:
#     paths-ignore:
#       - 'README.md'
#     branches: 
#       - main
#       - dev
  workflow_dispatch:

jobs:

  unittests:
    name: Graph DB and APP PyTest
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main
    - name: Get Python3
      uses: actions/setup-python@v1
      with:
        python-version: 3.7 

    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-1


    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools
        pip install -r requirements.txt

    - name: Run Gremlin Server
      run: |
        wget -q https://mirrors.sonic.net/apache/tinkerpop/3.4.11/apache-tinkerpop-gremlin-server-3.4.11-bin.zip
        unzip -q apache-tinkerpop-gremlin-server-3.4.11-bin.zip
        cd apache-tinkerpop-gremlin-server-3.4.11
        bin/gremlin-server.sh conf/gremlin-server-modern.yaml &
        sleep 5s

    - name: PyTest
      run: |
        export NEPTUNEDBRO=ws://localhost:8182/gremlin
        export STAGE=
        export S3_BUCKET=test-parth-bucket
        pytest -v -s

    - name: Stop Gremlin Server
      run: |
        pkill gremlin
        pkill java
